# Generated by Django 2.2.4 on 2023-01-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdash', '0002_pypie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('pypie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='appdash.Pypie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='appdash.User')),
            ],
        ),
    ]
